### ISSUE TITLE
Взаимоисключающие параграфы в постановке задачи

### ISSUE THREAD

**Issue by AnnaBerk** [ostrovok-team/code-challenge#5]
Добрый день. В постановке задачи:
"В Контенте мы занимаемся агрегацией отелей поставщиков (supplier), объединяя одинаковые отели от разных поставщиков в единую сущность (мета-отель)."
Далее:
"Объединить 1 и более отелей поставщика в один мета-отель"
В первом случае мы группируем сущность по признаку "отель"
Во втором случае мы уже не группируем по сущности "отель", т.к. "Объединить 1 и более отелей" говорит об обратном. Более того, "...отелей поставщикА" наводит на мысль, что общий признак теперь "поставщик". Или в постановке допущена опечатка и имелось ввиду "отелей поставщикОВ".
В любом случае, "объединяя одинаковые отели" и "Объединить 1 и более отелей поставщика" является взаимоисключающими параграфами.

**Comment by vanadium23** [comment]
Спасибо за обращение. Действительно речь идёт об объединение одного или более отелей между поставщикАМИ. Правда, жизнь оказывается гораздо разнообразнее и один и тот же поставщик может присылать одинаковые отели. Но мы это оставляем за рамками задачи.

**Comment by vanysiman** [comment]
Как я сюда попал

Сб, 7 янв. 2023 г. в 19:49, Anna Bernova ***@***.***>:
